import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import { JetBrains_Mono } from "next/font/google";
import StairTransition from "@/components/Animation/StairTransition";
import Footer from "@/components/Footer/Footer";

const JetBrainsMono = JetBrains_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-JetBrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${JetBrainsMono.variable}  antialiased`}>
       <div className="z-50 relative">
       <Header />
        <StairTransition/>
        {children}
        <Footer/>
       </div>
      </body>
    </html>
  );
}
